sequenceDiagram
    participant U as Utente
    participant App as RistoPOS
    participant DB as Sistema

    Note over U,DB: Inserimento Ordine
    U->>App: Seleziona piatto di pesce tramite tastierino.
