sequenceDiagram
    participant U as Utente
    participant App as App
    participant DB as Sistema

    Note over U,DB: Aggiunta Nuovo Tavolo
    U->>App: Seleziona 'modifica sale e tavoli'.
    U->>App: Configura un nuovo tavolo scegliendo forma, dimensioni, e al
